"""empty message

Revision ID: 28beb33b0616
Revises: b862eec6b709
Create Date: 2025-04-20 21:43:00.016187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28beb33b0616'
down_revision = 'b862eec6b709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attack_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('protocol_distribution', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('attack_distribution', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_results', schema=None) as batch_op:
        batch_op.drop_column('attack_distribution')
        batch_op.drop_column('protocol_distribution')
        batch_op.drop_column('attack_type')

    # ### end Alembic commands ###
